printWidth: 120
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: always
endOfLine: lf
